# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Continuous Integration

on:
  pull_request:
    branches: [ "main" ]

jobs:
  ci_verification:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Test Customer Service
      working-directory: ./user
      run : |
        npm ci
        npm test
    - name: Test Movie Service
      working-directory: ./movie
      run : |
        npm ci
        npm test
    - name: Test Review Service
      working-directory: ./review
      run : |
        npm ci
        npm test
